[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[all,standard]>=0.115.8",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.0",
    "sqlmodel>=0.0.24",
    "sqlalchemy>=2.0.0",
    "aiosqlite>=0.19.0",
    "asyncpg>=0.29.0",
    "psycopg2-binary>=2.9.9",
    "alembic>=1.13.1",
    "chromadb>=0.6.3",
    "langchain>=0.3.20",
    "langchain-community>=0.3.19",
    "python-multipart>=0.0.6",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt==4.0.1",
    "sse-starlette>=2.2.1",
    "asyncio>=3.4.3",
    "openai>=1.67.0",
    "langgraph>=0.3.21",
    "langchain-openai>=0.3.11",
    "greenlet>=3.1.1",
    "instructor>=1.7.8",
    "langgraph-checkpoint-sqlite>=2.0.6",
    "langgraph-checkpoint-postgres>=2.0.19",
    "psycopg[binary,pool]>=3.2.6",
    "psycopg-pool>=3.2.6",
    "langchain-google-genai>=2.1.2",
    "langchain-chroma>=0.2.2",
    "pandas>=2.2.3",
    "nltk>=3.9.1",
    "openpyxl>=3.1.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]
