"""Update models

Revision ID: 07d796459b21
Revises: f1944250ae1a
Create Date: 2025-04-02 17:21:33.161581

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07d796459b21"
down_revision: Union[str, None] = "f1944250ae1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trainee_id", sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(
            "fk_chat_conversations_trainee_id", "users", ["trainee_id"], ["id"]
        )

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.add_column(sa.Column("trainee_id", sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(
            "fk_chat_messages_trainee_id", "users", ["trainee_id"], ["id"]
        )
        batch_op.drop_column("sender_id")
        batch_op.drop_column("message")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("message", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("sender_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_chat_messages_trainee_id", type_="foreignkey")
        batch_op.drop_column("trainee_id")
        batch_op.drop_column("content")

    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_chat_conversations_trainee_id", type_="foreignkey")
        batch_op.drop_column("trainee_id")

    # ### end Alembic commands ###
