"""Update scenario customer expected queries

Revision ID: 160ff4bb10b3
Revises: 99298b867a0b
Create Date: 2025-04-18 22:45:55.851792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '160ff4bb10b3'
down_revision: Union[str, None] = '99298b867a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_customers', schema=None) as batch_op:
        batch_op.alter_column('expected_queries',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_customers', schema=None) as batch_op:
        batch_op.alter_column('expected_queries',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ### 