"""Update file uploads relationships

Revision ID: 191a381d7ae1
Revises: 789f880e8ff4
Create Date: 2025-04-18 23:36:34.299904

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "191a381d7ae1"
down_revision: Union[str, None] = "789f880e8ff4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_file_uploads')
    with op.batch_alter_table("file_uploads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uploaded_by_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_file_uploads_uploaded_by", "users", ["uploaded_by_id"], ["id"]
        )
        batch_op.drop_column("uploaded_by")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_uploads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uploaded_by", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_file_uploads_uploaded_by", type_="foreignkey")
        batch_op.drop_column("uploaded_by_id")

    # op.create_table('_alembic_tmp_file_uploads',
    # sa.Column('id', sa.VARCHAR(), nullable=False),
    # sa.Column('file_name', sa.VARCHAR(), nullable=False),
    # sa.Column('upload_date', sa.DATETIME(), nullable=False),
    # sa.Column('uploaded_by_id', sa.CHAR(length=32), nullable=False),
    # sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name='fk_file_uploads_uploaded_by'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
