"""Add scheme icon

Revision ID: 2e7c9d2d7ffd
Revises: 3f592302772e
Create Date: 2025-03-30 15:14:23.034505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e7c9d2d7ffd'
down_revision: Union[str, None] = '3f592302772e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ### 