"""Update session chat relationship

Revision ID: 44bc4500602c
Revises: 07d796459b21
Create Date: 2025-04-02 21:10:02.367786

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44bc4500602c"
down_revision: Union[str, None] = "07d796459b21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario_session_chats")
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scenario_session_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_scenario_session_chat",
            "scenario_sessions",
            ["scenario_session_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_scenario_session_chat", type_="foreignkey")
        batch_op.drop_column("scenario_session_id")

    op.create_table(
        "scenario_session_chats",
        sa.Column("scenario_session_id", sa.CHAR(length=32), nullable=False),
        sa.Column("chat_conversation_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_conversation_id"],
            ["chat_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_session_id"],
            ["scenario_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("scenario_session_id", "chat_conversation_id"),
    )
    # ### end Alembic commands ###
