"""Scenarios and schemes

Revision ID: 496e4fd2e329
Revises: 016eeb41372a
Create Date: 2025-03-18 23:36:19.642963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '496e4fd2e329'
down_revision: Union[str, None] = '016eeb41372a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheme_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scenarios_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_foreign_key('fk_scenarios_scheme_id_schemes', 'schemes', ['scheme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scenarios_scheme_id_schemes', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scenarios_scheme_id'))
        batch_op.drop_column('scheme_id')

    # ### end Alembic commands ### 