"""Add nullable end_timestamp

Revision ID: 49fafa049282
Revises: 8606e9ac152f
Create Date: 2025-03-27 16:55:04.310475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49fafa049282'
down_revision: Union[str, None] = '8606e9ac152f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_column('customer_id')
        batch_op.drop_column('scenario_id')

    with op.batch_alter_table('user_scenario_sessions', schema=None) as batch_op:
        batch_op.alter_column('end_timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_scenario_sessions', schema=None) as batch_op:
        batch_op.alter_column('end_timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.CHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.CHAR(length=32), nullable=False))

    # ### end Alembic commands ### 