"""Move temperature to customer scenario

Revision ID: 69b4645a2094
Revises: 49fafa049282
Create Date: 2025-03-27 22:57:03.150466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69b4645a2094'
down_revision: Union[str, None] = '49fafa049282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('customer_scenarios', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ### 