"""Update schema

Revision ID: 82f2512386ed
Revises: f250aba6ecee
Create Date: 2025-04-17 18:43:12.428657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82f2512386ed'
down_revision: Union[str, None] = 'f250aba6ecee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rubrics_settings')
    with op.batch_alter_table('rubrics_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('rubric_level_3')
        batch_op.drop_column('rubric_level_5')
        batch_op.drop_column('rubric_level_1')
        batch_op.drop_column('rubric_level_2')
        batch_op.drop_column('rubric_level_4')

    with op.batch_alter_table('scenario_customers', schema=None) as batch_op:
        batch_op.drop_column('feedback_ai')

    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.drop_column('trainer_feedback')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_feedback', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('scenario_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_ai', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('rubrics_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_level_4', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('rubric_level_2', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('rubric_level_1', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('rubric_level_5', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('rubric_level_3', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('rubric_prompt')

    op.create_table('_alembic_tmp_rubrics_settings',
    sa.Column('id', sa.VARCHAR(length=13), nullable=False),
    sa.Column('revision_date', sa.DATETIME(), nullable=False),
    sa.Column('rubric_name', sa.VARCHAR(), nullable=False),
    sa.Column('rubric_prompt', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ### 