"""Conversation scheme scenario relations

Revision ID: 8606e9ac152f
Revises: c17276b15f4c
Create Date: 2025-03-27 13:10:58.344713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8606e9ac152f'
down_revision: Union[str, None] = 'c17276b15f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ### 