"""Update schema

Revision ID: 99298b867a0b
Revises: a711b561e7da
Create Date: 2025-04-18 21:52:43.766187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99298b867a0b'
down_revision: Union[str, None] = 'a711b561e7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_column('messages')

    with op.batch_alter_table('chat_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))

    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics', sa.JSON(), nullable=True))
        batch_op.drop_column('metrics_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics_json', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('metrics')

    with op.batch_alter_table('chat_evaluations', schema=None) as batch_op:
        batch_op.drop_column('score')

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ### 