"""Update session

Revision ID: a711b561e7da
Revises: 82f2512386ed
Create Date: 2025-04-18 15:54:03.962927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a711b561e7da'
down_revision: Union[str, None] = '82f2512386ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.drop_column('metrics_json')

    # ### end Alembic commands ### 