"""Update file uploads schema

Revision ID: bc8c9aa3b3d9
Revises: 191a381d7ae1
Create Date: 2025-04-19 00:00:04.459233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc8c9aa3b3d9'
down_revision: Union[str, None] = '191a381d7ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.Enum('CSV', 'XLSX', name='fileuploadtype'), nullable=False))
        batch_op.add_column(sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_type')

    # ### end Alembic commands ### 