"""Update conversations

Revision ID: c17276b15f4c
Revises: 496e4fd2e329
Create Date: 2025-03-19 12:01:57.026608

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c17276b15f4c"
down_revision: Union[str, None] = "496e4fd2e329"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_id", sa.Uuid(), nullable=False))
        batch_op.add_column(
            sa.Column("customer_scenario_id", sa.Uuid(), nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_customer_scenario_id",
            "customer_scenarios",
            ["customer_scenario_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_customer_scenario_id", type_="foreignkey")
        batch_op.drop_column("customer_scenario_id")
        batch_op.drop_column("customer_id")

    # ### end Alembic commands ###
