"""Evaluator schemas

Revision ID: cb303035628f
Revises: 44bc4500602c
Create Date: 2025-04-07 22:36:05.004203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb303035628f'
down_revision: Union[str, None] = '44bc4500602c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_results', sa.JSON(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('trainee_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['scenario_sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_evaluations')
    # ### end Alembic commands ### 