"""Add trainer_feedback

Revision ID: e056f120f12e
Revises: e3d4a9d24537
Create Date: 2025-04-20 15:11:16.389550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e056f120f12e'
down_revision: Union[str, None] = 'e3d4a9d24537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_column('trainer_feedback')

    # ### end Alembic commands ### 