"""Assign files to scenarios

Revision ID: e3d4a9d24537
Revises: 1601b360d90a
Create Date: 2025-04-19 12:48:33.530123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3d4a9d24537'
down_revision: Union[str, None] = '1601b360d90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_file_upload_link',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('file_upload_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'file_upload_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_file_upload_link')
    # ### end Alembic commands ### 