"""Remove chat history from ScenarioCustomer

Revision ID: e5a8d82a3427
Revises: 2e7c9d2d7ffd
Create Date: 2025-03-30 16:30:41.134280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5a8d82a3427'
down_revision: Union[str, None] = '2e7c9d2d7ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('scenario_customers', schema=None) as batch_op:
        batch_op.drop_column('chat_history')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_history', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_column('messages')

    # ### end Alembic commands ### 