"""Update scenario session

Revision ID: f1944250ae1a
Revises: da6c8ce5b9be
Create Date: 2025-03-31 21:20:51.680041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1944250ae1a'
down_revision: Union[str, None] = 'da6c8ce5b9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('COMPLETED', 'FAILED', 'ABANDONED', 'TIMED_OUT', name='sessionstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ### 