"""Rubrics settings

Revision ID: f250aba6ecee
Revises: a1905f3fd3d0
Create Date: 2025-04-17 14:06:33.061794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f250aba6ecee'
down_revision: Union[str, None] = 'a1905f3fd3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubrics_settings',
    sa.Column('id', sa.Enum('ACCURACY', 'COMPREHENSION', 'TONE', 'CHAT_HANDLING', name='evaluationmetric'), nullable=False),
    sa.Column('revision_date', sa.DateTime(), nullable=False),
    sa.Column('rubric_level_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rubric_level_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rubric_level_3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rubric_level_4', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rubric_level_5', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rubric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.drop_column('trainer_feedback')

    op.drop_table('rubrics_settings')
    # ### end Alembic commands ### 